CREATE TABLE IF NOT EXISTS Users (
    UserId INT AUTO_INCREMENT,
    UserName VARCHAR(20) NOT NULL UNIQUE,
    UserNickName VARCHAR(20) NOT NULL UNIQUE,
    UserEmail VARCHAR(40) NOT NULL UNIQUE,
    Password VARCHAR (255) NOT NULL,
    PRIMARY KEY(UserId)
) 